# Generated by Django 5.0 on 2024-03-01 12:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_brokerage_broker"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brokerage",
            name="broker",
        ),
    ]
