# Generated by Django 5.0 on 2024-03-01 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_remove_brokerage_broker"),
    ]

    operations = [
        migrations.AddField(
            model_name="broker",
            name="brokerage",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.brokerage",
            ),
        ),
        migrations.AddField(
            model_name="salesagent",
            name="broker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.broker",
            ),
        ),
    ]
