# Generated by Django 5.0 on 2024-03-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_brokerage_brokerage_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="brokerage",
            name="contact_person",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="brokerage",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="brokerage",
            name="phone_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="brokerage",
            name="website",
            field=models.URLField(null=True),
        ),
    ]
