# Generated by Django 5.0 on 2024-03-01 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_brokerage_contact_person_brokerage_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broker",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brokers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
