# Generated by Django 5.0 on 2024-02-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("policy_number", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("sub_status", models.CharField(max_length=255, null=True)),
                ("start_date", models.DateField()),
                ("activation_date", models.DateField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
