# Generated by Django 5.0 on 2024-02-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="premium",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
