# Generated by Django 5.0 on 2024-02-17 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("max_number_of_people", models.IntegerField(default=1)),
                (
                    "scheme_type",
                    models.CharField(
                        choices=[
                            ("Car", "Car"),
                            ("Pet", "Pet"),
                            ("Group", "Group"),
                            ("Retail", "Retail"),
                            ("Credit", "Credit"),
                            ("Funeral", "Funeral"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "scheme_term",
                    models.CharField(
                        choices=[
                            ("Short Term", "Short Term"),
                            ("Long Term", "Long Term"),
                        ],
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SchemeGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("debit_order", "Debit Order"),
                            ("stop_order", "Stop Order"),
                            ("off_platform", "Off Platform"),
                            ("mpesa", "Mpesa"),
                            ("manual", "Manual"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("biannual", "Biannual"),
                            ("yearly", "Yearly"),
                            ("single", "Single"),
                        ],
                        max_length=255,
                    ),
                ),
                ("period_frequency", models.IntegerField(default=1)),
                (
                    "cycle_type",
                    models.CharField(
                        choices=[("member", "Member"), ("group", "Group")],
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "pricing_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pricing.pricingplan",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schemes.scheme"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
