# Generated by Django 5.0 on 2024-02-17 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schemes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheme",
            name="scheme_term",
        ),
    ]
