# Generated by Django 5.0 on 2024-02-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schemes", "0003_schemegroup_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="schemegroup",
            name="premium",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
