# Generated by Django 5.0 on 2024-02-17 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PricingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("base_premium", models.DecimalField(decimal_places=2, max_digits=100)),
                ("vat", models.DecimalField(decimal_places=2, max_digits=100)),
                (
                    "total_premium",
                    models.DecimalField(decimal_places=2, max_digits=100),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PricingPlanDependentPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("min_age", models.IntegerField(default=0)),
                ("max_age", models.IntegerField(default=0)),
                ("premium", models.DecimalField(decimal_places=2, max_digits=100)),
                ("cover_amount", models.DecimalField(decimal_places=2, max_digits=100)),
                (
                    "dependent_type",
                    models.CharField(
                        choices=[("Child", "Child"), ("Spouse", "Spouse")],
                        max_length=255,
                    ),
                ),
                (
                    "pricing_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pricing.pricingplan",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PricingPlanExtendedDependentPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("min_age", models.IntegerField(default=0)),
                ("max_age", models.IntegerField(default=0)),
                ("premium", models.DecimalField(decimal_places=2, max_digits=100)),
                ("cover_amount", models.DecimalField(decimal_places=2, max_digits=100)),
                (
                    "dependent_type",
                    models.CharField(
                        choices=[("Child", "Child"), ("Spouse", "Spouse")],
                        max_length=255,
                    ),
                ),
                (
                    "pricing_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pricing.pricingplan",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
