# Generated by Django 5.0 on 2024-02-17 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingPlanCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("short_term", "Short Term"),
                            ("long_term", "Long Term"),
                        ],
                        default="long_term",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="pricingplan",
            name="group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Car", "Car"),
                    ("Pet", "Pet"),
                    ("Group", "Group"),
                    ("Retail", "Retail"),
                    ("Credit", "Credit"),
                    ("Funeral", "Funeral"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pricingplan",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pricing.pricingplancategory",
            ),
        ),
    ]
