# Generated by Django 5.0 on 2024-02-17 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0002_pricingplancategory_pricingplan_group_and_more"),
        ("schemes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricingplan",
            name="category",
        ),
        migrations.RemoveField(
            model_name="pricingplan",
            name="group",
        ),
        migrations.AddField(
            model_name="pricingplan",
            name="plan_type",
            field=models.CharField(
                choices=[("Short Term", "Short Term"), ("Long Term", "Long Term")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pricingplan",
            name="scheme",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="schemes.scheme",
            ),
        ),
    ]
