# Generated by Django 5.0 on 2024-02-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pricing",
            "0003_remove_pricingplan_category_remove_pricingplan_group_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingplanextendeddependentpricing",
            name="dependent_type",
            field=models.CharField(default="Extended", max_length=255),
        ),
    ]
