# Generated by Django 5.0 on 2024-02-17 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0005_alter_pricingplanextendeddependentpricing_cover_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingplandependentpricing",
            name="pricing_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dependentpricing",
                to="pricing.pricingplan",
            ),
        ),
        migrations.AlterField(
            model_name="pricingplanextendeddependentpricing",
            name="pricing_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extendedpricing",
                to="pricing.pricingplan",
            ),
        ),
    ]
