# Generated by Django 5.0 on 2024-02-17 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0006_alter_pricingplandependentpricing_pricing_plan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingplan",
            name="base_cover",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.CreateModel(
            name="MainMemberPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("cover_amount", models.DecimalField(decimal_places=2, max_digits=100)),
                ("premium", models.DecimalField(decimal_places=2, max_digits=100)),
                (
                    "pricing_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mainmemberprices",
                        to="pricing.pricingplan",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
