# Generated by Django 5.0 on 2024-02-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0007_pricingplan_base_cover_mainmemberpricing"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainmemberpricing",
            name="dependent_type",
            field=models.CharField(default="Main Member", max_length=255),
        ),
    ]
