# Generated by Django 5.0 on 2024-02-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0008_mainmemberpricing_dependent_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainmemberpricing",
            name="cover_amount",
            field=models.DecimalField(
                choices=[
                    (150000, 150000),
                    (200000, 200000),
                    (260000, 260000),
                    (300000, 300000),
                ],
                decimal_places=2,
                max_digits=100,
            ),
        ),
    ]
