# Generated by Django 5.0 on 2024-02-24 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0003_membership_cover_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Beneficiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("Child", "Child"),
                            ("Spouse", "Spouse"),
                            ("Grand Parent", "Grand Parent"),
                            ("Parent", "Parent"),
                            ("Sister", "Sister"),
                            ("Brother", "Borther"),
                            ("Niece", "Niece"),
                            ("Nephew", "Nephew"),
                        ],
                        max_length=255,
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("id_number", models.CharField(max_length=255, null=True)),
                ("phone_number", models.CharField(max_length=255, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=255
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("guardian_name", models.CharField(max_length=255, null=True)),
                ("guardian_phone_number", models.CharField(max_length=255, null=True)),
                ("guardian_email", models.CharField(max_length=255, null=True)),
                (
                    "guardian_relationship",
                    models.CharField(
                        choices=[
                            ("Grand Parent", "Grand Parent"),
                            ("Parent", "Parent"),
                            ("Sister", "Sister"),
                            ("Brother", "Borther"),
                            ("Niece", "Niece"),
                            ("Nephew", "Nephew"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("guardian_date_of_birth", models.DateField(null=True)),
                ("guardian_address", models.CharField(max_length=255, null=True)),
                ("guarding_city", models.CharField(max_length=255, null=True)),
                ("guardian_country", models.CharField(max_length=255, null=True)),
                ("address", models.CharField(max_length=255, null=True)),
                ("city", models.CharField(max_length=255, null=True)),
                ("country", models.CharField(max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.membership",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Dependent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "dependent_type",
                    models.CharField(
                        choices=[("Child", "Child"), ("Spouse", "Spouse")],
                        max_length=255,
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("id_number", models.CharField(max_length=255, null=True)),
                ("phone_number", models.CharField(max_length=255, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=255
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "premium",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                (
                    "cover_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                ("address", models.CharField(max_length=255, null=True)),
                ("city", models.CharField(max_length=255, null=True)),
                ("country", models.CharField(max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.membership",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExtendedDependent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "dependent_type",
                    models.CharField(
                        choices=[
                            ("Grand Parent", "Grand Parent"),
                            ("Parent", "Parent"),
                            ("Sister", "Sister"),
                            ("Brother", "Borther"),
                            ("Niece", "Niece"),
                            ("Nephew", "Nephew"),
                        ],
                        max_length=255,
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("id_number", models.CharField(max_length=255, null=True)),
                ("phone_number", models.CharField(max_length=255, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=255
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "premium",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                (
                    "cover_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                ("address", models.CharField(max_length=255, null=True)),
                ("city", models.CharField(max_length=255, null=True)),
                ("country", models.CharField(max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.membership",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
