# Generated by Django 5.0 on 2024-02-24 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dependents", "0001_initial"),
        ("schemes", "0004_schemegroup_premium"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiary",
            name="scheme_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="schemes.schemegroup",
            ),
        ),
        migrations.AddField(
            model_name="dependent",
            name="scheme_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="schemes.schemegroup",
            ),
        ),
        migrations.AddField(
            model_name="extendeddependent",
            name="scheme_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="schemes.schemegroup",
            ),
        ),
    ]
