# Generated by Django 5.0 on 2024-02-18 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_policypremium_membership_policypremium_scheme_group"),
        ("schemes", "0003_schemegroup_policy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policypremium",
            name="scheme_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schemegroupmemberships",
                to="schemes.schemegroup",
            ),
        ),
    ]
